version: '2.1'

services:
  pinpoint-collector:
    container_name: pinpoint-collector
    hostname: collector
    image: dawidmalina/pinpoint-collector:1.6.2
    restart: always
    networks:
      hbase:
        ipv4_address: 172.28.0.30
    expose:
      - "9994"
      - "9995"
      - "9996"
    ports:
      - "9994:9994"
      - "9995:9995/tcp"
      - "9996:9996/tcp"
      - "9995:9995/udp"
      - "9996:9996/udp"
    environment:
      HBASE_HOST: zookeeper-1,zookeeper-2,zookeeper-3
      HBASE_PORT: 2181
      COLLECTOR_TCP_PORT: 9994
      COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
      COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
      CLUSTER_ENABLE: 'false'

  pinpoint-web:
    container_name: pinpoint-web
    hostname: web
    image: dawidmalina/pinpoint-web:1.6.2
    restart: always
    networks:
      hbase:
        ipv4_address: 172.28.0.50
    expose:
      - "8080"
    ports:
      - "3080:8080"
    environment:
      HBASE_HOST: zookeeper-1,zookeeper-2,zookeeper-3
      HBASE_PORT: 2181
      CLUSTER_ENABLE: 'false'
      ADMIN_PASSWORD: admin123

networks:
  hbase:
    external:
      name: dockerzookeeper_hbase
